# Model PreTraining

<b>Purpose: </b> Through this script, we will provide the RLHF model a starting point of knowledge on the game via training on annotated gamplay

In [1]:
import os
import json
from PIL import Image
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms


device = 'mps' if torch.backends.mps.is_available() else 'cuda' if torch.cuda.is_available() else 'cpu'
device = 'cpu'
print(f"Device: {device}")

Device: cpu


In [2]:
# Action mapping from strings to integers
ACTION_MAPPING = {
    "a": 0,
    "b": 1,
    "x": 2,
    "y": 3,
    "up": 4,
    "down": 5,
    "left": 6,
    "right": 7,
    "none": 8
}

### Creating the Data Loader

The dataloader is abnormal in the sense that each data point is actually a sequence of several. <br>
This is done to enable memory, vital for a storyline game like this.

In [3]:
class PokemonDataset(Dataset):
    def __init__(self, states_dir, actions_dir, annotations_dir, seq_length, transform=None):
        self.states_dir = states_dir                            # Reading in the states directory
        self.actions_dir = actions_dir                          # Reading in the actions directory
        self.annotations_dir = annotations_dir                  # Reading in the annotations directory
        self.transform = transform                              # Any image transformations 
        # Filter files to only include valid images
        self.states = sorted([f for f in os.listdir(states_dir) if f.endswith('.png')])
        self.actions = sorted([f for f in os.listdir(actions_dir) if f.endswith('.json')])
        self.annotations = sorted([f for f in os.listdir(annotations_dir) if f.endswith('.txt')])

        self.seq_length = seq_length                            # Reading in the desired seq length

    def __len__(self):
        return len(self.states) - self.seq_length               # Returns len of dataloader
    
    def __getitem__(self, idx):
        state_seq = []
        action_seq = []
        annotation_seq = []

        # Obtaining seq_length images, actions, and annotations
        for i in range(self.seq_length):

            # Retrieve image
            img_name = os.path.join(self.states_dir, self.states[idx + i])
            image = Image.open(img_name).convert('RGB')  # Ensure image is in RGB format
            if self.transform:
                image = self.transform(image) # Transform image
            state_seq.append(image)

            # Retrieve Action
            action_name = os.path.join(self.actions_dir, self.actions[idx + i])
            with open(action_name, 'r') as f:
                action = json.load(f)['action']
                action = ACTION_MAPPING[action] # Map annotation to int
                action_seq.append(action)

            #Retrieve Annotation
            annotation_name = os.path.join(self.annotations_dir, self.annotations[idx + i].replace('.png', '.txt'))
            with open(annotation_name, 'r') as f:
                annotations = [list(map(float, line.strip().split())) for line in f] # Ensure annotation is list of floats
                annotation_seq.append(annotations)

        # Convert state sequences to tensor
        state_seq_tensor = torch.stack(state_seq)

        # Convert action sequences to tensor
        action_seq_tensor = torch.tensor(action_seq, dtype=torch.long)

        max_annotations = 25
        padded_annotations = []
        for ann in annotation_seq:
            if len(ann) < max_annotations:
                ann += [[-1, 0, 0, 0, 0]] * (max_annotations - len(ann))
            elif len(ann) > max_annotations:
                ann = ann[:max_annotations]
            padded_annotations.append(ann)
        annotation_seq_tensor = torch.tensor(padded_annotations, dtype=torch.float32)

        
        return state_seq_tensor, action_seq_tensor, annotation_seq_tensor

Initialise Dataloader

In [4]:
# Chosen transformation
transform = transforms.Compose([
    transforms.Resize((640, 640)),
    transforms.ToTensor()
])

seq_length = 3
dataset = PokemonDataset('annotated_images/images', 'annotated_images/actions', 'annotated_images/labels', seq_length, transform=transform)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [5]:
# Ensuring the data is loaded fine
for i, (s, action,ann) in enumerate(dataloader):
    print(f'{i}')

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159


### Model Training

Initialise the model

In [7]:
from models.PokemonModelLSTM import PokemonModelLSTM
# Setting Hyperparameters
num_actions = 9  # (Total Number of Actions: [A, B, X, Y, Up, Down, Left, Right, None]) (Excluding Start, Select, L, R to reduce model complexity)
input_size = 32 * 160 * 160
hidden_size = 128
num_layers = 2
num_epochs = 20

# Initialising model
model = PokemonModelLSTM(input_size, hidden_size, num_layers, num_actions).to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()


In [9]:
# Load the model and optimizer state if a checkpoint exists
if os.path.exists("models/pokemon_model_lstm.pth"):
    state_dict = torch.load("models/pokemon_model_lstm.pth")
    model.load_state_dict(state_dict)

In [50]:
for epoch in range(num_epochs):
    model.train()
    for i, (state_seq, action_seq, annotation_seq) in enumerate(dataloader):
        print(f"Currently processing Epoch {epoch}, batch {i}")
        state_seq, action_seq, annotation_seq = state_seq.to(device), action_seq.to(device), annotation_seq.to(device)
        optimizer.zero_grad()

        # Forward pass
        output = model(state_seq, annotations=annotation_seq)
        print(output)

        # Calculate loss
        action_seq = action_seq[:, -1]  # Get the last action in the sequence for each batch
        loss = criterion(output, action_seq)
        
        # Backward pass and optimization
        loss.backward()
        optimizer.step()
    
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}")
    
    # Update the model after every iteration
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'loss': loss,
    }, 'models/pokemon_model_lstm.pth')


Currently processing Epoch 0, batch 0
tensor([[ 0.0308, -0.1191, -0.0902, -0.1370,  0.0812, -0.0936,  0.1237, -0.0408,
          0.0355],
        [ 0.0366, -0.1285, -0.0558, -0.0974,  0.0594, -0.0538,  0.1232, -0.0423,
          0.0221]], grad_fn=<AddmmBackward0>)
Currently processing Epoch 0, batch 1
tensor([[-0.1183,  0.0126, -0.0460, -0.0742,  0.1392,  0.5365,  0.0110, -0.0427,
         -0.0459],
        [-0.1206,  0.0149, -0.0404, -0.0724,  0.1354,  0.5379,  0.0132, -0.0478,
         -0.0471]], grad_fn=<AddmmBackward0>)
Currently processing Epoch 0, batch 2
tensor([[-1.1838e-01, -1.5093e-03, -1.2338e-01, -1.1112e-01,  3.5574e-02,
          4.3935e-01, -3.3920e-04, -1.1299e-01,  1.0197e-01],
        [-1.1831e-01, -1.7742e-03, -1.2292e-01, -1.1153e-01,  3.5085e-02,
          4.4031e-01, -1.9599e-04, -1.1208e-01,  1.0237e-01]],
       grad_fn=<AddmmBackward0>)
Currently processing Epoch 0, batch 3
tensor([[-0.1273, -0.0069, -0.1495, -0.1324,  0.1162,  0.4369, -0.0398, -0.1250,
       