# Model PreTraining

<b>Purpose: </b> Through this script, we will provide the RLHF model a starting point of knowledge on the game via training on annotated gamplay

In [11]:
import os
import json
from PIL import Image
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms


device = 'mps' if torch.backends.mps.is_available() else 'cuda' if torch.cuda.is_available() else 'cpu'
device = 'cpu'
print(f"Device: {device}")

Device: cpu


In [12]:
# Action mapping from strings to integers
ACTION_MAPPING = {
    "a": 0,
    "b": 1,
    "x": 2,
    "y": 3,
    "up": 4,
    "down": 5,
    "left": 6,
    "right": 7,
    "none": 8
}

### Creating the Data Loader

The dataloader is abnormal in the sense that each data point is actually a sequence of several. <br>
This is done to enable memory, vital for a storyline game like this.

In [19]:
class PokemonDataset(Dataset):
    def __init__(self, states_dir, actions_dir, annotations_dir, seq_length, transform=None):
        self.states_dir = states_dir                            # Reading in the states directory
        self.actions_dir = actions_dir                          # Reading in the actions directory
        self.annotations_dir = annotations_dir                  # Reading in the annotations directory
        self.transform = transform                              # Any image transformations 
        self.states = sorted(os.listdir(states_dir))            # Reading in the ordered states from the os
        self.actions = sorted(os.listdir(actions_dir))          # Reading in the ordered actions from the os
        self.annotations = sorted(os.listdir(annotations_dir))  # Reading in the ordered actions from the os

        self.seq_length = seq_length                            # Reading in the desired seq length

    def __len__(self):
        return len(self.states) - self.seq_length               # Returns len of dataloader
    
    def __getitem__(self, idx):
        state_seq = []
        action_seq = []
        annotation_seq = []

        # Obtaining seq_length images, actions, and annotations
        for i in range(self.seq_length):

            # Retrieve image
            img_name = os.path.join(self.states_dir, self.states[idx + i])
            image = Image.open(img_name).convert('RGB')  # Ensure image is in RGB format
            if self.transform:
                image = self.transform(image) # Transform image
            state_seq.append(image)

            # Retrieve Action
            action_name = os.path.join(self.actions_dir, self.actions[idx + i])
            with open(action_name, 'r') as f:
                action = json.load(f)['action']
                action = ACTION_MAPPING[action] # Map annotation to int
                action_seq.append(action)

            #Retrieve Annotation
            annotation_name = os.path.join(self.annotations_dir, self.annotations[idx + i].replace('.png', '.txt'))
            with open(annotation_name, 'r') as f:
                annotations = [list(map(float, line.strip().split())) for line in f] # Ensure annotation is list of floats
                annotation_seq.append(annotations)

        # Convert state sequences to tensor
        state_seq_tensor = torch.stack(state_seq)

        # Convert action sequences to tensor
        action_seq_tensor = torch.tensor(action_seq, dtype=torch.long)

        max_annotations = 19  # Set the max_annotations to the correct length
        padded_annotations = []
        for ann in annotation_seq:
            if len(ann) < max_annotations:
                ann += [[-1, 0, 0, 0, 0]] * (max_annotations - len(ann))
            elif len(ann) > max_annotations:
                ann = ann[:max_annotations]
            padded_annotations.append(ann)
        annotation_seq_tensor = torch.tensor(padded_annotations, dtype=torch.float32)

        
        return state_seq_tensor, action_seq_tensor, annotation_seq_tensor

Initialise Dataloader

In [20]:
# Chosen transformation
transform = transforms.Compose([
    transforms.Resize((640, 640)),
    transforms.ToTensor()
])

seq_length = 3
dataset = PokemonDataset('annotated_images/images', 'annotated_images/actions', 'annotated_images/labels', seq_length, transform=transform)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [22]:
# Ensuring the data is loaded fine
for s, action,ann in dataloader:
    print(s, action,ann)

tensor([[[[[0.8196, 0.8118, 0.8078,  ..., 0.6667, 0.6667, 0.6706],
           [0.8196, 0.8118, 0.8078,  ..., 0.6235, 0.6157, 0.6392],
           [0.8157, 0.8078, 0.8078,  ..., 0.6510, 0.6471, 0.6471],
           ...,
           [0.6235, 0.5725, 0.5961,  ..., 0.5098, 0.5020, 0.5176],
           [0.6706, 0.6118, 0.5137,  ..., 0.5255, 0.5098, 0.4902],
           [0.6745, 0.5725, 0.4275,  ..., 0.5686, 0.6275, 0.6431]],

          [[0.8196, 0.8118, 0.8078,  ..., 0.7137, 0.7137, 0.7176],
           [0.8196, 0.8118, 0.8078,  ..., 0.6706, 0.6627, 0.6863],
           [0.8157, 0.8078, 0.8078,  ..., 0.6980, 0.6941, 0.6941],
           ...,
           [0.6706, 0.6196, 0.6275,  ..., 0.6392, 0.6235, 0.6392],
           [0.7059, 0.6471, 0.5490,  ..., 0.6353, 0.6235, 0.5961],
           [0.7098, 0.6039, 0.4588,  ..., 0.6549, 0.7176, 0.7294]],

          [[0.8196, 0.8118, 0.8078,  ..., 0.7843, 0.7804, 0.7804],
           [0.8196, 0.8118, 0.8078,  ..., 0.7294, 0.7216, 0.7451],
           [0.8157, 0.8078

ValueError: expected sequence of length 5 at dim 2 (got 19)

In [15]:
for state_seq, action_seq, annotation_seq in dataloader:
    print("State Sequence:", state_seq)
    print("Action Sequence:", action_seq)
    print("Annotation Sequence:", annotation_seq)
    break  # To check the output for the first batch only

State Sequence: tensor([[[[[0.0706, 0.0706, 0.0706,  ..., 0.1255, 0.1020, 0.0863],
           [0.0588, 0.0588, 0.0549,  ..., 0.1137, 0.0902, 0.0745],
           [0.0510, 0.0471, 0.0431,  ..., 0.1373, 0.1059, 0.0824],
           ...,
           [0.0941, 0.1451, 0.2275,  ..., 0.4000, 0.3569, 0.3255],
           [0.1059, 0.1647, 0.2510,  ..., 0.4196, 0.3765, 0.3451],
           [0.1059, 0.1686, 0.2627,  ..., 0.4314, 0.3882, 0.3569]],

          [[0.0745, 0.0745, 0.0706,  ..., 0.0824, 0.0667, 0.0588],
           [0.0627, 0.0588, 0.0510,  ..., 0.0627, 0.0549, 0.0471],
           [0.0549, 0.0471, 0.0353,  ..., 0.0824, 0.0627, 0.0510],
           ...,
           [0.1176, 0.2039, 0.3294,  ..., 0.5255, 0.4745, 0.4353],
           [0.1255, 0.2118, 0.3373,  ..., 0.5255, 0.4745, 0.4392],
           [0.1176, 0.2039, 0.3294,  ..., 0.5137, 0.4627, 0.4275]],

          [[0.0902, 0.0863, 0.0824,  ..., 0.0706, 0.0667, 0.0667],
           [0.0863, 0.0745, 0.0588,  ..., 0.0431, 0.0471, 0.0510],
          

In [16]:
class PokemonModelLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_actions):
        super(PokemonModelLSTM, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, stride=2, padding=1)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=2, padding=1)
        self.lstm = nn.LSTM(input_size=32*160*160, hidden_size=hidden_size, num_layers=num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_actions)
    
    def forward(self, x, annotations=None):
        batch_size, seq_len, C, H, W = x.size()
        x = x.view(batch_size * seq_len, C, H, W)
        x = torch.relu(self.conv1(x))
        x = torch.relu(self.conv2(x))
        x = x.view(batch_size, seq_len, -1)
        x, _ = self.lstm(x)
        x = self.fc(x[:, -1, :])
        return x

### Model Training

Initialise the model

In [17]:
# Setting Hyperparameters
num_actions = 9  # (Total Number of Actions: [A, B, X, Y, Up, Down, Left, Right, None]) (Excluding Start, Select, L, R to reduce model complexity)
input_size = 32 * 160 * 160
hidden_size = 128
num_layers = 2
num_epochs = 20

# Initialising model
model = PokemonModelLSTM(input_size, hidden_size, num_layers, num_actions).to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()


In [18]:
for epoch in range(num_epochs):
    model.train()
    for i, (state_seq, action_seq, annotation_seq) in enumerate(dataloader):
        print(f"Currently processing Epoch {epoch}, batch {i}")
        state_seq, action_seq, annotation_seq = state_seq.to(device), action_seq.to(device), annotation_seq.to(device)
        optimizer.zero_grad()

        # Forward pass
        output = model(state_seq, annotations=annotation_seq)
        print(output)

        # Calculate loss
        action_seq = action_seq[:, -1]  # Get the last action in the sequence for each batch
        loss = criterion(output, action_seq)
        
        # Backward pass and optimization
        loss.backward()
        optimizer.step()
    
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}")

# Save the trained model
torch.save(model.state_dict(), 'models/pokemon_model_lstm.pth')

Currently processing Epoch 0, batch 0
tensor([[-0.1047,  0.0169, -0.1409, -0.0992,  0.0110, -0.1554, -0.0928,  0.0329,
         -0.0035],
        [-0.0790,  0.0401, -0.0845, -0.0888,  0.0430, -0.1162, -0.0784,  0.0412,
         -0.0436]], grad_fn=<AddmmBackward0>)
Currently processing Epoch 0, batch 1
tensor([[-0.3232, -0.3266, -0.1521, -0.1585,  0.4662, -0.2459, -0.3566, -0.0158,
          0.0942],
        [-0.3234, -0.3269, -0.1523, -0.1583,  0.4660, -0.2460, -0.3567, -0.0159,
          0.0944]], grad_fn=<AddmmBackward0>)
Currently processing Epoch 0, batch 2
tensor([[-0.2546, -0.3103, -0.2405, -0.1948,  0.3748, -0.2344, -0.2043, -0.0538,
         -0.0039],
        [-0.2546, -0.3103, -0.2405, -0.1948,  0.3748, -0.2344, -0.2043, -0.0538,
         -0.0039]], grad_fn=<AddmmBackward0>)
Currently processing Epoch 0, batch 3
tensor([[-0.1486, -0.3123, -0.2943, -0.2230,  0.4295, -0.2570, -0.1676, -0.0759,
         -0.0443],
        [-0.1486, -0.3123, -0.2943, -0.2230,  0.4295, -0.2570, -0.1

ValueError: expected sequence of length 19 at dim 2 (got 5)